### ISSUE TITLE
tab out long black screen problem

### ISSUE THREAD

**Issue by omarmassari** [braycarlson/alphares#13]
when tab out of Fortinite I have a very long black screen

**Comment by 1GabsFps** [comment]
you need to change your monitor resolution to the resolution that you put in the game

**Comment by braycarlson** [comment]
I'm not sure this is an alphares issue, but a consequence of using a stretched resolution. This issue could be due to your operating system, graphics drivers or Fortnite. I don't recommend it, but you might also have change some settings in your graphics card control panel to accommodate for the stretched resolution. If you decide to do that, then please do so at your own risk. Other than that, it might be best to not use alphares or a stretched resolution. Sorry.
