### ISSUE TITLE
Black bar on screen

### ISSUE THREAD

**Issue by Bizbutnoneofyours** [braycarlson/alphares#17]
I put on alphares, but theres a black bar on my screen and it really bothers me when playing, is there a fix for this?

**Comment by braycarlson** [comment]
I'm not sure this is an alphares issue, but a consequence of using a stretched resolution. This issue could be due to your operating system, graphics drivers or Fortnite. I don't recommend it, but you might also have change some settings in your graphics card control panel to accommodate for the stretched resolution. If you decide to do that, then please do so at your own risk. Other than that, it might be best to not use alphares or a stretched resolution. Sorry.
