### ISSUE TITLE
invetory

### ISSUE THREAD

**Issue by Mizkoo** [braycarlson/alphares#24]
You cant switch weapons in youre invetory if you are on controller

**Comment by braycarlson** [comment]
This is not an alphares issue, but a consequence of using a stretched resolution. Unfortunately, there is nothing that I can do my end to fix this. This issue could be due to your operating system, graphics drivers or Fortnite. I don't recommend it, but you might also have to change some settings in your graphics card control panel to accommodate for the stretched resolution. If you decide to do that, then please do so at your own risk. Other than that, it might be best to not use alphares or a stretched resolution. Sorry.
