### ISSUE TITLE
Icons not working

### ISSUE THREAD

**Issue by UserProblems** [braycarlson/alphares#4]
The application itself works amazingly but after i installed this i cant seem to open or click on the desktop icons on the left side of my screen

**Comment by braycarlson** [comment]
I'm not sure this is an alphares issue (because all it does is change a settings file for Fortnite), but a consequence of using a stretched resolution. So, this issue could be due to your operating system, graphics drivers or Fortnite itself. I don't recommend it, but you might also have change some settings in your graphics card control panel to accommodate for the stretched resolution. Other than that, it might be best to not use alphares in that case. Sorry.
