### ISSUE TITLE
Tab out problem

### ISSUE THREAD

**Issue by silviosisca** [braycarlson/alphares#5]
If you open a new window and you have an altered resolution, it breaks it and u have to reset the game to let it work again

**Comment by braycarlson** [comment]
I'm not sure this is an alphares issue (because all it does is change a settings file for Fortnite), but a consequence of using a stretched resolution. So, this issue could be due to your operating system, graphics drivers or Fortnite itself. It might be best to not use alphares in that case. Sorry.
