### ISSUE TITLE
Alphares wont work

### ISSUE THREAD

**Issue by Jozex381** [braycarlson/alphares#6]
When i set streeched res on alphares it says"configuration file could not be found" and it doesnt apply what should i do?

**Comment by hborgblox** [comment]
when i set a res en then when i start fortnite half of my screen be fortnite att it freeze lag there in the loading screen

**Comment by braycarlson** [comment]
> When i set streeched res on alphares it says"configuration file could not be found" and it doesnt apply what should i do?

Are you playing on Windows? Have you run Fortnite previously on that PC before using alphares? It is possible that Fortnite changed the location or the name of the settings file. If so, I will have to investigate, however, I do not have Fortnite installed. If possible, can you do the following:

If you're on Windows: 
- Close Fortnite.
- Press: <kbd>Win</kbd> + <kbd>R</kbd> to open a "Run" window. 
- In the box, type: `%localappdata%` and press <kbd>Enter</kbd>. 
- Navigate to: "FortniteGame/Saved/Config/WindowsClient/". 

Is there a file named "GameUserSettings.ini"?

> when i set a res en then when i start fortnite half of my screen be fortnite att it freeze lag there in the loading screen

This should be a new issue, but this also not an alphares issue. All alphares does is change the settings for Fortnite. This might be due to your operating system, graphics drivers or Fortnite itself. So, it might be best to not use alphares in that case. Sorry.
